version: '3.3'

services:
  # DATABASE SERVER
  mariadb:
    image: mariadb:latest
    container_name: nestjs_db
    networks:
      - nestjs_stack
    volumes:
      - ./mariadb:/var/lib/mysql
      - ./docker/mariadb/my.cnf.d:/etc/mysql/my.cnf.d
      - ./docker/mariadb/db-setup:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
networks:
  nestjs_stack:
volumes:
  db_data:
